version: 0.0.{build}
os: Visual Studio 2019
    
build:
  project: MitchEngineUWP.sln
  parallel: true
  verbosity: normal
branches:
  only:
    - master
before_build:
  - git submodule init
  - git submodule update
  - ./GenerateSolutionUWP.bat
  - ./CopyAssets.bat
  - cd ThirdParty
  - ./GenerateSolutions.bat
  - cd ..
  - nuget restore