name: Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        buildconfig: [Game_Win64_Release, Editor_Release]
        include:
          - os: windows-2019
            shell: cmd
            compiler: cl
            target: Windows

    steps:
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - uses: suisei-cn/actions-download-file@v1
        id: downloadfile
        name: Grab the project setup file
        with:
          url: "https://raw.githubusercontent.com/wobbier/MitchEngine/master/NewProjectSetup.bat"
          target: ./

      - name: Generate a new project
        shell: cmd
        run: call NewProjectSetup.bat EmptyProject

      - name: Compile Tools
        if: ${{ matrix.buildconfig == 'Game_Win64_Release' }}
        shell: cmd
        run: msbuild /property:Configuration="Editor_Release"

      - name: Compile Project
        shell: cmd
        run: msbuild /property:Configuration="${{matrix.buildconfig}}"

      - name: Copy Assets
        shell: cmd
        run: call CopyAssets.bat

      - name: Copy Editor Assets
        shell: cmd
        continue-on-error: true
        run: |
          robocopy ".build/Release/Assets" ".build\\Editor_Release\\Assets" *.* /w:0 /r:1 /v /E
          robocopy "Engine/Tools" ".build\\Editor_Release\\Engine\\Tools" *.* /w:0 /r:1 /v /E

      - name: Archive Editor
        if: ${{ matrix.buildconfig == 'Editor_Release' }}
        uses: actions/upload-artifact@v2
        with:
          name: EmptyProject v${{github.run_number}} - Editor
          path: |
            .build/${{matrix.buildconfig}}
            !.build/${{matrix.buildconfig}}/AppX
            !.build/${{matrix.buildconfig}}/Tools/**/*.*
            !.build/${{matrix.buildconfig}}/*.lib
            !.build/${{matrix.buildconfig}}/*.pdb
            !.build/${{matrix.buildconfig}}/*.exp
            !.build/${{matrix.buildconfig}}/*.log
            .build/${{matrix.buildconfig}}/Tools/Optick.exe
            .build/${{matrix.buildconfig}}/Tools/Win64/*.*

      - name: Cook Assets
        if: ${{ matrix.buildconfig == 'Game_Win64_Release' }}
        shell: cmd
        run: |
          cd ".build/Editor_Release/"
          call Havana.exe -CompileAssets
          cd ../../

      - name: Copy Cooked Assets
        if: ${{ matrix.buildconfig == 'Game_Win64_Release' }}
        shell: cmd
        continue-on-error: true
        run: |
          robocopy ".build/Editor_Release/Assets" ".build\\Game_Win64_Release\\Assets" *.* /w:0 /r:1 /v /E

      - name: Archive Build
        if: ${{ matrix.buildconfig == 'Game_Win64_Release' }}
        uses: actions/upload-artifact@v2
        with:
          name: EmptyProject v${{github.run_number}} - ${{matrix.buildconfig}}
          path: |
            .build/${{matrix.buildconfig}}
            .build/${{matrix.buildconfig}}/Assets
            !.build/${{matrix.buildconfig}}/AppX
            !.build/${{matrix.buildconfig}}/*.lib
            !.build/${{matrix.buildconfig}}/*.pdb
            !.build/${{matrix.buildconfig}}/*.exp
            !.build/${{matrix.buildconfig}}/*.log
            !.build/${{matrix.buildconfig}}/**/*.png
            !.build/${{matrix.buildconfig}}/**/*.jpg
            !.build/${{matrix.buildconfig}}/**/*.frag
            !.build/${{matrix.buildconfig}}/**/*.vert
            !.build/${{matrix.buildconfig}}/**/*.var
            !.build/${{matrix.buildconfig}}/**/*.sh
